# Generated by Django 4.2.3 on 2023-07-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depoimentos',
            new_name='Depoimento',
        ),
    ]
